---
bases:
  - ../../base
  - ../../base/services
  - ../dbs/postgres

resources:
  - ./secrets.yaml
  - ./migratepg-job.yaml

commonLabels:
  jacksondev: '1'

images:
  - name: boxyhq/jackson
    newTag: 1.12.0
